version: "3"

services:

  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    depends_on:
      - "postgres"
      - "mailcatcher"
      - "redis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/mychat
      - gems:/gems

  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"

  redis:
    image: 'redis:6.0.4'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
  postgres:
  gems:
  redis:
