default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  host: postgres

development:
  <<: *default
  database: mychat_development

test:
  <<: *default
  database: mychat_test

production:
  <<: *default
  database: mychat_production
  username: mychat
  password: <%= ENV['MYCHAT_DATABASE_PASSWORD'] %>
